In [2]:
import numpy as np
from IPython.display import display

## Benefits of using Numpy arrays

Numpy arrays offer the following benefits over Python lists for operating on numerical data:

- **Ease of use**: You can write small, concise, and intuitive mathematical expressions. rather than using loops & custom functions.
- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops that are interpreted at runtime

Here's a comparison of dot products performed using Python loops vs. Numpy arrays on two vectors with a million elements each.

In [ ]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2

print(result)

833332333333500000
CPU times: user 186 ms, sys: 987 µs, total: 187 ms
Wall time: 187 ms


In [ ]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 2.49 ms, sys: 98 µs, total: 2.58 ms
Wall time: 2.28 ms


833332333333500000

# Creating a NumPy Array

In [3]:
# we can create a numpy array (matrix and vectors) using array method
x = [2, 3, 4, 5, 6]  
np_array_vect = np.array([2, 3, 4, 5, 6]) # row vector of five elements
print("vector")
print("type : {} , shape : {} ".format(type(np_array_vect),np_array_vect.shape))

vector
type : <class 'numpy.ndarray'> , shape : (5,) 


In [ ]:
# creating a matrix
matrix = np.array([[2,4],
                   [8,10],
                   [14,16]],dtype=np.float)
print("Shape ",matrix.shape,"size ",matrix.size) # matrix shape (rows , columns)
matrix

Shape  (3, 2) size  6


array([[ 2.,  4.],
       [ 8., 10.],
       [14., 16.]])

# Numerical Computing with Python and Numpy

![](https://i.imgur.com/mg8O3kd.png)

In [27]:
# creating matrix using zeros method
zeros_vect = np.zeros(7) # vector of 7 zeros
display('zeros_vect',zeros_vect)
zeros_matrix = np.zeros((2,2,3)) # 5 by 4 matrix of zeros
display('zeros_matrix')
display(zeros_matrix)

'zeros_vect'

array([0., 0., 0., 0., 0., 0., 0.])

'zeros_matrix'

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
zeros_matrix.size

12

In [37]:
# creating matrix using ones method
zeros_vect = np.ones(8)*20 # vector of 7 ones
print("ones_vect")
display(zeros_vect)
zeros_matrix = np.ones((8,8))*53
print("ones_matrix")
display(zeros_matrix)

ones_vect


array([20., 20., 20., 20., 20., 20., 20., 20.])

ones_matrix


array([[53., 53., 53., 53., 53., 53., 53., 53.],
       [53., 53., 53., 53., 53., 53., 53., 53.],
       [53., 53., 53., 53., 53., 53., 53., 53.],
       [53., 53., 53., 53., 53., 53., 53., 53.],
       [53., 53., 53., 53., 53., 53., 53., 53.],
       [53., 53., 53., 53., 53., 53., 53., 53.],
       [53., 53., 53., 53., 53., 53., 53., 53.],
       [53., 53., 53., 53., 53., 53., 53., 53.]])

In [41]:
eye_Matrix = np.eye(8,8)
eye_Matrix

array([[0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
# using rand method
randomuni = np.random.rand(2, 3) # generates 2 by 3 matrix uniformly distributed 
print("random matrix uniform distributed")
display(randomuni)
# uniform ditribution : http://mathworld.wolfram.com/UniformDistribution.html
randomnorm = np.random.randn(2, 3)
# normal ditribution : http://mathworld.wolfram.com/NormalDistribution.html
print("random matrix normally distributed")
display(randomnorm)

random matrix uniform distributed


array([[0.82148921, 0.70164337, 0.45841543],
       [0.59631409, 0.38231631, 0.1770205 ]])

random matrix normally distributed


array([[-0.64408701, -0.96299073,  0.99900857],
       [-1.12302639,  0.84600929, -0.76383171]])

In [ ]:
# create matrix of random ints in specefic range 
# check : https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html#numpy.random.randint
randomint = np.random.randint(low=5,high=20,size=(5,4))
#randomint = np.random.randint(low=5,high=20,size=(5,4)).astype('float')
print("random matrix of integers")
display(randomint)

random matrix of integers


array([[ 9, 10, 11,  9],
       [13,  5, 16,  5],
       [19, 17, 14, 17],
       [ 7,  6,  8, 15],
       [ 9, 10, 16,  7]])

# Array reshaping

In [57]:
# Reshape 1D to 2D Array
nums = np.arange(1, 17)

display("nums = ",nums)
nums2 = nums.reshape(2, -1)
print('nums reshaped intp 4 by 4 matrix')
display(nums2)

two_d = np.array([[2,3,4], [5,6,7]])

display('two_d = ', two_d)

flat=two_d.reshape(2,-1)
display('two_d converted into flat = ', flat)

print("two_d shape : {} flat shape : {}".format(two_d.shape,flat.shape))

# more examples : https://www.w3resource.com/numpy/manipulation/reshape.php

'nums = '

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

nums reshaped intp 4 by 4 matrix


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

'two_d = '

array([[2, 3, 4],
       [5, 6, 7]])

'two_d converted into flat = '

array([[2, 3, 4],
       [5, 6, 7]])

two_d shape : (2, 3) flat shape : (2, 3)


In [63]:
three_d = np.array([[[2,3,4], [5,6,7], [8,9,10]]])
three_d.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# numpy array operations

In [ ]:
Df = np.array([4352, 233, 3245, 256, 2394])
print("average : ",Df.mean())
print("sum : ",Df.sum())
print("min : ",Df.min())
print("max : ",Df.max())
print("position of min value ",Df.argmin()) # position of the minimum value
print("position of max value ",Df.argmax()) # position of the Maximum value

# element wise operations
twod = np.array(([10,2,3],[40,5,6],[7,80,9]))
print("twod - 10")
display(twod-10)
print("twod * 5")
display(twod * 5)
print("log twod")
display(np.log(twod))
print("exp twod")
display(np.exp(twod))

average :  2096.0
sum :  10480
min :  233
max :  4352
position of min value  1
position of max value  0
twod - 10


array([[ 0, -8, -7],
       [30, -5, -4],
       [-3, 70, -1]])

twod * 5


array([[ 50,  10,  15],
       [200,  25,  30],
       [ 35, 400,  45]])

log twod


array([[2.30258509, 0.69314718, 1.09861229],
       [3.68887945, 1.60943791, 1.79175947],
       [1.94591015, 4.38202663, 2.19722458]])

exp twod


array([[2.20264658e+04, 7.38905610e+00, 2.00855369e+01],
       [2.35385267e+17, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 5.54062238e+34, 8.10308393e+03]])

In [ ]:
# test whether none of the elements of a given array is zero
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [ ]:
# test if any of the elements of a given array is non-zero
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test if any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test if any of the elements of a given array is non-zero:")
print(np.any(x))

Original array:
[1 0 0 0]
Test if any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test if any of the elements of a given array is non-zero:
False


In [ ]:
# test element-wise for NaN of a given array
a = np.array([1, 0, np.nan, 5,np.nan])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))
print(np.sum(np.isnan(a))) # get how many nanas

Original array
[ 1.  0. nan  5. nan]
Test element-wise for NaN:
[False False  True False  True]
2


In [ ]:
# element wise comparison
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [ ]:
# np.sum ()
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [66]:
# appending new rows and columns
a = np.array([[1, 2, 3],[-1,-2,-3]])
b = np.array([[10, 11, 12]])
append_rows = np.append (a, b,axis=0)
append_cols = np.append (a, [[10], [11]],axis=1)
print("append new row")
display(append_rows)
print("append new column")
display(append_cols)

append new row


array([[ 1,  2,  3],
       [-1, -2, -3],
       [10, 11, 12]])

append new column


array([[ 1,  2,  3, 10],
       [-1, -2, -3, 11]])

In [ ]:
# custom function for element wise operation
# convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# indexing and slicing

The notation and its results can seem confusing at first, so take your time to experiment and become comfortable with it. Use the cells below to try out some examples of array indexing and slicing, with different combinations of indices and ranges. Here are some more examples demonstrated visually:

<img src="https://scipy-lectures.org/_images/numpy_indexing.png" width="360">

In [13]:
nums3d = np.array(([1,2,3],
                   [4,5,6],
                   [7,8,9]))  
print("shape is ",nums3d.shape)
nums3d

shape is  (3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# get elemetns by index
print("element at first row and first column = {}".format(nums3d[0,0]*20))
print("element at second row and last column = {}".format(nums3d[1,-3]))
print("last column = {}".format(nums3d[:,1]))
print("upper left matrix \n {}".format(nums3d[:2,:2]))
# To get several and indepent columns
display("first and last column",nums3d[:,[0,2]])
# To get several and indepent rows
display("first and last row",nums3d[[0,2],:])

element at first row and first column = 20
element at second row and last column = 4
last column = [2 5 8]
upper left matrix 
 [[1 2]
 [4 5]]


'first and last column'

array([[1, 3],
       [4, 6],
       [7, 9]])

'first and last row'

array([[1, 2, 3],
       [7, 8, 9]])

#### quiz  : write a python function to get middle element of square array

### Flattening numpy arrays

In [ ]:
array = np.array(([1,2,3],[4,5,6],[7,8,9]))
display('before flattening',array,'shape',array.shape)
vector=array.flatten()
display('after flattening',vector,'shape',vector.shape)

'before flattening'

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

'shape'

(3, 3)

'after flattening'

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

'shape'

(9,)

### np.where()
we may want to search for indexes and values that satisfy some conditions

In [68]:
array=np.random.randint(low=1,high=50,size=(5,5))
display(array)
# assume we want to threshold this array values lower than 25 will be zero and values higher than 25 will be ones
display('thresholding',np.where(array>25,5,2))
# select values based on conditions
display('values in array satisfies some conditions',array[np.where(np.logical_and(array<25,array>10))])

array([[28, 34, 17, 28, 36],
       [35,  3, 18, 48,  5],
       [46, 26, 27,  1, 12],
       [32, 49, 30, 20, 10],
       [11, 15, 12, 41, 31]])

'thresholding'

array([[5, 5, 2, 5, 5],
       [5, 2, 2, 5, 2],
       [5, 5, 5, 2, 2],
       [5, 5, 5, 2, 2],
       [2, 2, 2, 5, 5]])

'values in array satisfies some conditions'

array([17, 18, 12, 20, 11, 15, 12])

### Vectorize custom functions
we can get vectorized function for our custom function to run in vectorized mode over all array elements

In [ ]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

### apply function along axis

In [ ]:
def minmax(axis):
    return max(axis)-min(axis)

array=np.random.randint(low=10,high=100,size=(5,5))
display(array)
display('min - max of every of row',np.apply_along_axis(func1d=minmax,axis=0,arr=array))

array([[77, 31, 71, 89, 64],
       [86, 86, 94, 98, 61],
       [52, 33, 50, 92, 85],
       [18, 30, 18, 44, 24],
       [35, 86, 49, 99, 54]])

'min - max of every of row'

array([68, 56, 76, 55, 61])

# To enjoy the full numpy functions list 

[Numpy Functions](https://numpy.org/doc/stable/reference/routines.html)

In [72]:
%whos

Variable        Type        Data/Info
-------------------------------------
a               ndarray     2x3: 6 elems, type `int64`, 48 bytes
append_cols     ndarray     2x4: 8 elems, type `int64`, 64 bytes
append_rows     ndarray     3x3: 9 elems, type `int64`, 72 bytes
array           ndarray     5x5: 25 elems, type `int64`, 200 bytes
b               ndarray     1x3: 3 elems, type `int64`, 24 bytes
display         function    <function display at 0x7fecaadb33b0>
eye_Matrix      ndarray     8x8: 64 elems, type `float64`, 512 bytes
flat            ndarray     2x3: 6 elems, type `int64`, 48 bytes
np              module      <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
np_array_vect   ndarray     5: 5 elems, type `int64`, 40 bytes
nums            ndarray     16: 16 elems, type `int64`, 128 bytes
nums2           ndarray     2x8: 16 elems, type `int64`, 128 bytes
nums2d          ndarray     3x3: 9 elems, type `int64`, 72 bytes
nums3d          ndarray     3x3: 9 elems, type `int64